# Generated by Django 6.0.3 on 2026-04-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunt',
            old_name='date_retour_prevue',
            new_name='date_retour',
        ),
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.CharField(choices=[('roman', 'Roman'), ('science', 'Science'), ('histoire', 'Histoire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
